# This is a basic workflow that is manually triggered

name: Manual workflow

# Controls when the action will run. Workflow runs when manually triggered using the UI
# or API.
on:
  release:
    types: [published]
  
# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "greet"
  job_a:
    # The type of runner that the job will run on
    runs-on: Eriteym-runners
    environment: dev   
    if: |
        github.event_name == 'release' && startsWith(github.ref,'refs/tags/v')
       
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - name: Check out repository code
        uses: actions/checkout@v4

      - name: Create .env file
        run: |
          echo "Generating .env file"
          echo "${{ vars.ENV_FILE_DEV }}" >> .deploy/.env_backend
          echo "DB_PASSWORD=${{ secrets.DB_PASSWORD }}" >> .deploy/.env_backend

      - name: check .env_file
        run: cat .deploy/.env_backend

      - name: lowercase DOCKER_IMAGE
        run: |
          echo "DOCKER_IMAGE=$(echo ghcr.io/${{github.repository}}:${{github.ref_name}} | tr '[:upper:]' '[:lower:]')" >> ${GITHUB_ENV}
          
    # Runs a single command using the runners shell
      - name: Send greeting
        run: echo "Hello ${DOCKER_IMAGE}"

  job_b:  
    needs: [job_a]
  # The type of runner that the job will run on
    runs-on: Eriteym-runners
    if: |
      github.event_name == 'workflow_dispatch' || 
      startsWith(github.ref,'refs/release-**')
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # Runs a single command using the runners shell
    - name: Send greeting manual
      run: echo "Hello ${{ inputs.name }} im manual"

